googleAnalytics: "G-9MEWF2N2MJ"
baseurl: /
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
params:
  contentTypeName: post
  defaultTheme: dark
  showMenuItems: 2
  showReadingTime: yes
languages:
  en:
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: archive
          name: Archive
          url: /archive
    menuMore: Show more
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        logoHomeLink: /
        logoText: Big Human
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: Data and Research
    title: Big Human
    writtenBy: Written by
rssFullText: true
headers:
  - for: /*
    values:
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
      X-Content-Type-Options: nosniff
      Content-Security-Policy-Report-Only: >-
        default-src 'none'; form-action 'none'; frame-ancestors 'none';
        report-uri https://bighuman.report-uri.com/r/d/csp/enforce
      Referrer-Policy: strict-origin-when-cross-origin
      Strict-Transport-Security: max-age=2592000
      Feature-Policy: >-
        vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none';
        push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none';
        magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none';
        fullscreen 'none'; payment 'none'





